feat: add format to Telegram
activepieces/activepieces pull request #2598
Opened 2023-09-10 17:09 UTC by tanoggy

Add format support for Telegram (Markdown and HTML format)
Fix some spell
![image](https://github.com/activepieces/activepieces/assets/24206229/92528c26-f5f6-4e97-9224-91656e7d2d1a)

2023-09-10 17:09 UTC, tanoggy commented
hi @AbdulTheActivePiecer, please review my pull request

2023-09-10 20:18 UTC, abuaboud commented
@allcontributors please add @tanoggy for plugin

2023-09-10 20:21 UTC, abuaboud requested changes
Please also bump the version in package.json to 0.3.4

2023-09-10 20:21 UTC, abuaboud commented on packages/pieces/telegram-bot/src/lib/action/send-text-message.action.ts
> +        console.log(ctx)
Please remove this

2023-09-10 20:21 UTC, abuaboud commented on packages/pieces/telegram-bot/src/lib/action/send-text-message.action.ts
> +            required: true,
required: false

2023-09-10 20:21 UTC, abuaboud commented on packages/pieces/telegram-bot/src/lib/action/send-text-message.action.ts
> +                parse_mode: ctx.propsValue['format']
Please add `ctx.propsValue['format'] ?? 'MarkdownV2' ` as the field is no longer required

2023-09-10 23:47 UTC, tanoggy commented
> Please also bump the version in package.json to 0.3.4

please review again

2023-09-11 11:18 UTC, abuaboud approved these changes

2023-09-11 11:19 UTC, merged