feat(Vtiger): Create Record Action / Delete Record  Action / Get Record Action / Make Api Call  Action/ Search Record Action / Update Record Action / New or Updated Records
activepieces/activepieces pull request #3550
Opened 2024-01-04 10:28 UTC by kanarelo

## What does this PR do?

This PR introduces the piece for vtiger. 

VTiger is an opensource php based CRM, with community and enterprise versions. Enterprise version has a new and updated API, but the community version has a slighly outdated API.

This Piece attempts to bring over features as seen on make.com.

https://www.make.com/en/integrations/vtiger

Commisioned by George - https://community.activepieces.com/t/vtiger-self-hosted-pieces/248/9

ANNOUNCEMENT=true

2024-01-04 10:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/activepieces/activepieces?pullRequest=3550) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/activepieces/activepieces?pullRequest=3550) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/activepieces/activepieces?pullRequest=3550) it.</sub>

2024-01-05 01:28 UTC, abuaboud requested changes

2024-01-05 01:28 UTC, abuaboud commented on packages/pieces/vtiger/src/lib/actions/search2.html
Is this used? If not can we remove it please

2024-01-05 01:28 UTC, abuaboud commented on packages/backend/.env
can you please rollback these changes

2024-01-11 09:40 UTC, kanarelo commented on packages/backend/.env
sure

2024-01-11 09:40 UTC, kanarelo commented on packages/pieces/vtiger/src/lib/actions/search2.html
Yes, I think I added that by mistake

2024-01-12 14:01 UTC, kanarelo commented on packages/pieces/vtiger/src/lib/actions/search2.html
fixed

2024-01-12 14:02 UTC, kanarelo commented on packages/backend/.env
fixed, check and let me know

2024-01-13 13:57 UTC, abuaboud approved these changes

2024-01-13 14:06 UTC, abuaboud approved these changes

2024-01-13 14:06 UTC, abuaboud approved these changes

2024-01-13 14:07 UTC, merged