feat: adds frame.io app, adds triggers for project, comment and asset creation
activepieces/activepieces pull request #3622
Opened 2024-01-13 10:37 UTC by kanarelo

## What does this PR do?

Adds support for frame.io triggers 
- asset.created
- project.created
- comment.created

2024-01-13 13:50 UTC, abuaboud requested changes

2024-01-13 13:50 UTC, abuaboud commented on packages/pieces/frame/src/lib/triggers/register-trigger.ts
> +    // const { team_id } = context.propsValue
I think this is by mistake right?

2024-01-13 13:50 UTC, abuaboud commented on packages/pieces/frame/src/index.ts
> +  logoUrl: "https://asset.brandfetch.io/idKZYqdo-7/idxIQ0UveY.svg", //TODO: Change URL
https://cdn.activepieces.com/pieces/frameio.png

2024-01-15 05:38 UTC, kanarelo commented on packages/pieces/frame/src/lib/triggers/register-trigger.ts
> +    // const { team_id } = context.propsValue
Sure, let me fix that

2024-01-16 00:05 UTC, abuaboud approved these changes

2024-01-16 00:08 UTC, merged