feat(google-drive): search for file / folder action
activepieces/activepieces pull request #3635
Opened 2024-01-15 08:49 UTC by kanarelo

## What does this PR do?

Fixes # (issue)

ANNOUNCEMENT=true

2024-01-15 19:32 UTC, abuaboud approved these changes

2024-01-16 00:04 UTC, abuaboud requested changes

2024-01-16 00:04 UTC, abuaboud commented on packages/pieces/google-drive/src/lib/action/get-file-by-name.ts
> +    folderId: Property.ShortText({
Can we make this dropdown like the trigger?

2024-01-16 14:38 UTC, kanarelo commented on packages/pieces/google-drive/src/lib/action/get-file-by-name.ts
> +    folderId: Property.ShortText({
Fixed

2024-01-19 06:23 UTC, kanarelo commented
@abuaboud let me know if I should close this. Thanks.

2024-01-19 09:14 UTC, kishanprmr commented
Hello @kanarelo ,

PR #3632 has moved to the Community folder. Can you please update your feature branch?

Let me know if you face any issues.

2024-01-19 11:08 UTC, kanarelo commented
> Hello @kanarelo ,
> 
> PR #3632 has moved to the Community folder. Can you please update your feature branch?
> 
> Let me know if you face any issues.

Hey Yeah, I am having a couple of build issues, but I will tel you if and when i can build it.

2024-01-19 12:26 UTC, abuaboud approved these changes

2024-01-19 12:26 UTC, merged