chore: add text wrap to test output window and format thrown error message
activepieces/activepieces pull request #4061
Opened 2024-02-29 10:39 UTC by bigfluffycookie

## What does this PR do?

Added wrap-text for Test output window and prettified nested thrown errors for readability.

**Before**
![Screenshot 2024-02-28 165742](https://github.com/activepieces/activepieces/assets/54935347/bbc2a6cc-749c-4ad7-a4a1-17ce91ca0dbd)

**After**
![Screenshot 2024-02-28 165615](https://github.com/activepieces/activepieces/assets/54935347/a9928e68-23b6-45b6-bdbe-a96adfdc1b39)
![Screenshot 2024-02-28 170755](https://github.com/activepieces/activepieces/assets/54935347/71520f81-7465-4ee6-b4d4-d40949bd964c)

Note:
- Did not add word wrapping for extended output module

2024-02-29 10:40 UTC, bigfluffycookie commented on packages/ui/common/src/lib/components/json-view/json-view.component.html
> +    <pre *ngIf="!highlight" [innerHTML]="_content | outputLog" class="ap-px-4 thin-scrollbars ap-py-3 wrap-text">
I removed ap-break-all, I am assuming it was supposed to the wrap-text but it wasnt working so to avoid conflicts in the future I took it out.

2024-02-29 10:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/activepieces/activepieces?pullRequest=4061) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/activepieces/activepieces?pullRequest=4061) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/activepieces/activepieces?pullRequest=4061) it.</sub>

2024-02-29 11:34 UTC, AbdulTheActivePiecer commented on packages/ui/common/src/lib/components/json-view/json-view.component.scss
> +}
Hi there, could you please use tailwind in the html template instead of this? "ap-whitespace-nowrap ap-break-normal "

2024-02-29 11:37 UTC, AbdulTheActivePiecer commented on packages/ui/feature-builder-test-steps/src/lib/test-action/test-action.component.ts
> +    return `${acc}${indentation}Error ${index}: ${current.trim()}\n`;
make this:
`return `${acc}${indentation}Error ${index+1}: ${current.trim()}\n`;`

2024-02-29 11:41 UTC, AbdulTheActivePiecer requested changes
Hi there Leyla, thank you for contributing to Activepieces 🎉 

I requested some minor changes if you don't mind, could you please do them?

2024-02-29 12:49 UTC, bigfluffycookie commented on packages/ui/common/src/lib/components/json-view/json-view.component.scss
> +}
Hi,theres some issue with using tailwinds break see: https://github.com/tailwindlabs/tailwindcss/discussions/10545

Ive tried the min width solution but it still does not work, I guess thats why the original ap-break-all was not working either

2024-03-03 11:47 UTC, AbdulTheActivePiecer approved these changes

2024-03-03 11:47 UTC, merged