feat(linear): enrich actions output
activepieces/activepieces pull request #4536
Opened 2024-04-23 15:14 UTC by AdamSelene

## What does this PR do?

Enrich various Linear actions output to include the actual object (e.g. created issue, project, comment, etc.) instead of a useless internal ID

2024-04-23 20:05 UTC, abuaboud requested changes
Hi @AdamSelene 

Why not remove the proxy object and increase the minor version, the new flows will have to manual upgrade the pieces :D

2024-04-23 20:50 UTC, AdamSelene commented
@abuaboud done!

2024-04-23 22:55 UTC, abuaboud approved these changes

2024-04-24 12:17 UTC, abuaboud approved these changes

2024-04-24 15:17 UTC, merged