fix(notion): Fix Issue with Skipped Items within the Same Minute Interval
activepieces/activepieces pull request #4690
Opened 2024-05-14 11:08 UTC by kishanprmr

## What does this PR do?

Fixes #4671

2024-05-15 08:41 UTC, abuaboud requested changes

2024-05-15 08:41 UTC, abuaboud commented on packages/pieces/community/notion/src/index.ts
> +	minimumSupportedRelease: '0.26.2',
Can you please revert this

2024-05-15 08:41 UTC, abuaboud commented on packages/pieces/community/notion/src/lib/triggers/new-database-item.ts
> +                after: startDate,
shouldn't we use the one with >= instead?

2024-05-15 08:41 UTC, abuaboud commented on packages/pieces/community/notion/src/lib/triggers/updated-database-item.ts
> +                after: startDate,
same here

2024-05-15 12:38 UTC, kishanprmr commented on packages/pieces/community/notion/src/index.ts
> +	minimumSupportedRelease: '0.26.2',
fixed it.

2024-05-16 10:55 UTC, abuaboud approved these changes

2024-05-16 15:38 UTC, merged