Develop
activepieces/activepieces pull request #5010
Opened 2024-06-30 09:39 UTC by saifmohamedsv

## Ask HTTP Codepilot

- Creating the button for asking the HTTP request writer
- Handling the code generation writer in the HTTP piece view
-  Creating service for code generation
- Handle setting, getting generated code from dialog

2024-06-30 17:07 UTC, AbdulTheActivePiecer requested changes

2024-06-30 17:07 UTC, AbdulTheActivePiecer commented on packages/shared/src/lib/websocket/index.ts
> +    REQUEST_WRITE = 'REQUEST_WRITE',
Please rename this to GENERATE_HTTP_REQUEST

2024-06-30 17:07 UTC, AbdulTheActivePiecer commented on packages/ui/feature-builder-right-sidebar/src/lib/http-request-writer/http-request-writer.component.ts
> +  codeGeneratorTooltip = codeGeneratorTooltip;
Please rename those to be showGeneratedHttpRequest$ and httpRequestGeneratorTooltip, make sure everything is renamed in this component so everything has "httpRequest" instead of "code".

2024-06-30 17:07 UTC, AbdulTheActivePiecer commented on packages/ui/feature-builder-right-sidebar/src/lib/http-request-writer/request-writer-dialog/request-writer-dialog.component.html
> +  >Fill HTTP requets with AI
Rename this to "Http Request Copilot"

2024-06-30 17:07 UTC, AbdulTheActivePiecer commented on packages/ui/feature-builder-right-sidebar/src/lib/http-request-writer/request-writer-dialog/request-writer-dialog.component.html
> +        <ng-template matStepLabel>Code Iteration</ng-template>
what's code iteration ?

2024-06-30 17:07 UTC, AbdulTheActivePiecer commented on packages/ui/feature-builder-right-sidebar/src/lib/http-request-writer/request-writer-dialog/request-writer-dialog.component.html
> +      Use Code
Rename to "Use Generated Request"

2024-06-30 17:07 UTC, AbdulTheActivePiecer commented on packages/ui/feature-builder-right-sidebar/src/lib/http-request-writer/request-writer-dialog/request-writer-dialog.component.html
> +    Let AI help you write code for this step. Write your prompt below to get
Let AI generate an HTTP request for this step.

2024-07-01 11:41 UTC, saifmohamedsv commented on packages/ui/feature-builder-right-sidebar/src/lib/http-request-writer/request-writer-dialog/request-writer-dialog.component.html
> +        <ng-template matStepLabel>Code Iteration</ng-template>
It's a step from the code copilot but I was afraid of removing it

2024-07-02 13:36 UTC, closed without merging