Fix/loops 15 9 2024
activepieces/activepieces pull request #5615
Opened 2024-09-15 16:00 UTC by AbdulTheActivePiecer

## What does this PR do?

Fixes # (issue)

2024-09-17 03:45 UTC, abuaboud requested changes
I am working on simplifying flow run utils

2024-09-17 03:57 UTC, abuaboud commented on packages/react-ui/src/styles.css
> -    --input: 220 13% 91%;
Why did we change this? reverted it

2024-09-17 04:20 UTC, abuaboud requested changes

2024-09-17 04:20 UTC, abuaboud commented on packages/react-ui/src/app/builder/builder-hooks.ts
> +        sideEffect?.();
removed sideEffect it's not needed

2024-09-17 04:20 UTC, abuaboud commented on packages/react-ui/src/features/flow-runs/lib/flow-run-utils.ts
> +function findStepParents(
This function not required, I strongly keep suggest flowHelper, I replaced it here to use flowHelper

2024-09-17 04:20 UTC, abuaboud commented on packages/react-ui/src/app/builder/builder-hooks.ts
>  export const createBuilderStore = (initialState: BuilderInitialState) =>
Note: it won't auto select failed step, If you open run from the run table.

2024-09-17 04:20 UTC, abuaboud commented on packages/react-ui/src/app/builder/builder-header.tsx
> +        {!embedState.hideLogoInBuilder && (
![image](https://github.com/user-attachments/assets/399bc4e0-fc0c-4b6f-9a72-f0578c239a13)

Please remove, this is laptop resolution

2024-09-17 04:20 UTC, abuaboud commented on packages/react-ui/src/app/builder/flow-canvas/widgets/index.tsx
> +                  setRun(run, flowVersion, () => {
No need to pass sideEffect function

It can be written like this

```ts
                setRun={(run, flowVersion) => {
                  setRun(run, flowVersion);
                  const failedStep = run.steps
                    ? flowRunUtils.findFailedStep(run)
                    : null;
                  if (failedStep) {
                    fitView(
                      flowCanvasUtils.createFocusStepInGraphParams(
                        failedStep,
                      ),
                    );
                  }
                }}
```

2024-09-18 08:32 UTC, AbdulTheActivePiecer commented on packages/react-ui/src/app/builder/flow-canvas/widgets/index.tsx
> +                  setRun(run, flowVersion, () => {
I moved this away to the builder itself, so we don't have to worry about it every time the run changes.

2024-09-18 08:53 UTC, merged