fix: chat ui enhancements
activepieces/activepieces pull request #5893
Opened 2024-10-21 02:33 UTC by anasbarg

## What does this PR do?

Fixes # (issue)

2024-10-21 10:58 UTC, abuaboud requested changes

2024-10-21 10:58 UTC, abuaboud commented on packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts
> +    }),
I would move this down, and give it a default value

2024-10-21 10:58 UTC, abuaboud commented on packages/react-ui/src/app/routes/chat/index.tsx
> +const MessagesList = React.memo(({ messagesRef, messages, chatUI, sendingError, isSending, flowId, sendMessage, setSelectedImage }: { messagesRef: React.RefObject<HTMLDivElement>, messages: Messages,
This can be another file and you can also extract the type to it's line

2024-10-21 10:58 UTC, abuaboud commented on packages/server/api/src/app/flows/flow/human-input/human-input.controller.ts
> +// TODO: add an endpoint for Chat UI options
I think they are done?

2024-10-21 15:58 UTC, abuaboud commented
My notes would be:

- Bot name should be somewhere else.
- Animation for "How I can help you" is incorrect, the cursor color and the cursor should no longer show after it's done.

![image](https://github.com/user-attachments/assets/412a2ce7-8c96-409d-a4f9-90a48c6bce08)
- Feel like there is dirt in loading.
-  Code should looks better maybe in a box?
![image](https://github.com/user-attachments/assets/cd216e28-465d-4327-a52e-d8777c2c3237)

2024-10-21 19:26 UTC, anasbarg commented
✅ Enhanced code block appearance + copy button for code blocks

<img width="1663" alt="Screenshot_2024-10-21_at_9 27 41_PM" src="https://github.com/user-attachments/assets/100d521a-7144-41e5-a612-831cd624203a">

✅ Enhance initial animation for large screens

https://github.com/user-attachments/assets/238aad8d-c7e6-45e9-8615-b692d6f7540a


✅ Enhance initial animation for smaller screens

https://github.com/user-attachments/assets/e50d8a21-38af-47bf-bd4f-b0fd5ef47239

2024-10-22 19:25 UTC, anasbarg commented
✅ Enhanced code block appearance + copy button for code blocks

![image](https://github.com/user-attachments/assets/ddb2faed-f390-4cb1-9f0b-b77a846ccbcf)

✅ Fix image dialog flickering on close/ESC

2024-10-23 08:55 UTC, abuaboud submitted a review, later dismissed

2024-10-23 09:18 UTC, abuaboud approved these changes

2024-10-23 09:19 UTC, merged