Pieces/airtable actions
activepieces/activepieces pull request #685
Opened 2023-02-26 18:00 UTC by kanarelo

## What does this PR do?

Fixes #435 

## Type of change

- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist

- I haven't checked if my PR needs changes to the documentation

2023-03-05 18:27 UTC, AbdulTheActivePiecer commented on packages/pieces/apps/src/lib/airtable/common/index.ts
> +              return { value: table, label: table.name };
Can you please change the value to only take the table's id ? because the fields' names and descriptions can change, and that would unset the select in the frontend, because the selected value would for example have a field called "A" and when the user changes its name to "B" it wouldn't be the same value in the select.

2023-03-05 18:27 UTC, AbdulTheActivePiecer commented on packages/pieces/apps/src/lib/airtable/common/index.ts
> +      (table as AirtableTable).fields.map((field: AirtableField) => {
Once the table is replaced wit the table id, you would have to get the table and its field from the API.

2023-03-05 18:27 UTC, AbdulTheActivePiecer commented on packages/pieces/apps/src/lib/airtable/common/index.ts
> +          description: field.description,
can you please add a note for date fields in params.description that "Expected format: mmmm d,yyyy" ?

2023-03-06 12:48 UTC, kanarelo commented on packages/pieces/apps/src/lib/airtable/common/index.ts
> +      (table as AirtableTable).fields.map((field: AirtableField) => {
Not sure I've understood, but I am taking a look

2023-03-12 08:14 UTC, AbdulTheActivePiecer commented on packages/pieces/airtable/src/lib/common/index.ts
> +      console.debug("fetch airtable list response", response)
remove this debug since it could contain sensitive data, please.

2023-03-12 09:09 UTC, AbdulTheActivePiecer requested changes

2023-03-12 09:09 UTC, AbdulTheActivePiecer commented on packages/pieces/airtable/src/lib/common/index.ts
> +    console.debug("Create record response", response)
remove this debug since it could contain sensitive data, please

2023-03-12 09:09 UTC, AbdulTheActivePiecer commented on packages/pieces/airtable/src/lib/common/index.ts
> +    console.debug("fetch airtable response", response)
remove this debug since it could contain sensitive data, please

2023-03-12 09:09 UTC, AbdulTheActivePiecer commented on packages/pieces/airtable/src/lib/common/index.ts
> +    refreshers: ["authentication", "base", "table"],
"table" should be "tableId"

2023-03-12 09:09 UTC, AbdulTheActivePiecer commented on packages/pieces/airtable/src/lib/common/index.ts
> +          tableId: table as unknown as string
replace "table" with "tableId"

2023-03-12 09:09 UTC, AbdulTheActivePiecer commented on packages/pieces/airtable/src/lib/common/index.ts
> +
I can't find this endpoint anywhere, I would suggest you replace it with this. 
`async fetchTable({ token, baseId, tableId }: { token: string, baseId: string, tableId: string }) {
    const response = await airtableCommon.fetchTableList({token,baseId});
    return response.find(t=>t.id === tableId)!;
  }`

2023-03-12 09:09 UTC, AbdulTheActivePiecer commented on packages/pieces/airtable/src/lib/common/models.ts
> +  multipleSelects: Property.MultiSelectDropdown,
switch this to Property.StaticMultiSelectDropdown

2023-03-12 09:09 UTC, AbdulTheActivePiecer commented on packages/pieces/airtable/src/lib/common/index.ts
> +            //TODO: implement multiselect
remove this

2023-03-12 09:09 UTC, AbdulTheActivePiecer commented on packages/pieces/airtable/src/lib/common/index.ts
> +          if (field.type === "singleSelect") {
make the condition (field.type === "singleSelect" || field.type === "multipleSelects")

2023-03-15 12:56 UTC, AbdulTheActivePiecer approved these changes

2023-03-15 13:05 UTC, merged