Pieces/Xero
activepieces/activepieces pull request #905
Opened 2023-03-28 05:54 UTC by kanarelo

## What does this PR do?

Fixes #904

2023-03-29 02:20 UTC, abuaboud requested changes

2023-03-29 02:20 UTC, abuaboud commented on packages/pieces/xero/src/lib/actions/create-invoice.ts
> +    contact_id: props.contact_id(true),
Let's replace contact_id with contact_name (required) and contact_email (optional).

2023-03-29 02:20 UTC, abuaboud commented on packages/pieces/xero/src/lib/actions/create-invoice.ts
> +    date: Property.ShortText({
This should be optional

2023-03-29 02:20 UTC, abuaboud commented on packages/pieces/xero/src/lib/actions/create-invoice.ts
> +    due_date: Property.ShortText({
Please add default value, ideally we should replace it with date picker.

2023-03-29 02:20 UTC, abuaboud commented on packages/pieces/xero/src/lib/common/props.ts
> +    displayName: 'Tenant ID',
Let's rename it to `Organization`

2023-03-29 02:20 UTC, abuaboud commented on packages/pieces/xero/src/index.ts
> +  logoUrl: "https://upload.wikimedia.org/wikipedia/en/9/9f/Xero_software_logo.svg",
Let's replace this to `https://cdn.activepieces.com/pieces/xero.png`

2023-04-04 06:35 UTC, kanarelo commented on packages/pieces/xero/src/lib/actions/create-invoice.ts
> +    date: Property.ShortText({
Ok

2023-04-04 15:58 UTC, kanarelo commented
@abuaboud cleared. You can test now

2023-04-04 22:03 UTC, merged